### PR TITLE
Do not allow putting blocks over 2MiB in blockstore

### PR DESCRIPTION
**Pull request by gammazero**
Addresses issue https://github.com/ipfs/go-ipfs/issues/7021

### CODE REVIEW

**Comment by ribasushi** [comment]
@gammazero this seems like a too-low-level spot to institute a limit. Blockstores are used for things exchanged though mechanisms other than Bitswap. Off the top of my head this could affect:
- various generators in go-ipld-prime (@warpfork correct me if I am wrong and you do not care about this interface)
- advanced ADL-like structures used in e.g. Peergos ( @ianopolous please chime in whether a change like this will affect your encrypted slabs )

**Comment by ianopolous** [comment]
Thanks for the mention, @ribasushi. We already enforce a 0.5 MiB max block size in our block store in Peergos currently (we're being conservative). We'd love to increase that to 1 MiB, but couldn't get a strong steer on whether that would be safe *forever*.

**Comment by gammazero** [comment]
@ribasushi I read the [original issue](https://github.com/ipfs/go-ipfs/issues/7021) to indicate that we do not want to allow a block over 2 MiB into the block store, as an absolute upper limit.  So, I assumed this would need to be at a very low level and higher level protocols, transports, etc. will set their own limits.

There really was not much detail in that issue, so my assumption is likely wrong or the issue is no longer applicable.  If either of those is the case, then I will close this PR and edit or close the issue.

**Comment by ribasushi** [comment]
@Stebalien please weigh in on https://github.com/ipfs/go-ipfs-blockstore/pull/61#issuecomment-731665527 when time permits.

**Comment by Stebalien** [comment]
I believe I was thinking about banning this in the go-ipfs block API (and the add options) instead of at the blockstore level itself. This limitation is a side effect of the IPFS protocol as it exists today, not necessarily IPLD itself.

While I'd prefer not to add this blanket restriction to the default blockstore, it might make sense to implement it as a wrapper. That would make it easy for applications to specify a size policy without enforcing a default policy (alternatively, it can just be added as an optional/configurable limit to the default blockstore.

**Comment by Stebalien** [comment]
@ianopolous I believe the general consensus is that 1MiB is "safe". That is, transports should support up to 2MiB blocks, so if you target 1MiB chunks and maybe add some keys/padding on top, it should always work.

**Comment by gammazero** [comment]
Closing this PR as it is not the how we want to provide this functionality.  I will update the original issue with comments from this review.  Thank you everyone.

**Pull request closed without merging**
