### PR TITLE
Add test to maintain Put contract of calling Has first

### PR DESCRIPTION
**Pull request by shazow**
Hi there, I'm working with @MichaelMure on some of Infura's IPFS backend, and we realized that we're relying on the implementation detail of blockstore that `Put` checks `Has` first. I want to add a test to maintain this implementation detail, or at least inform us if it's going to go away so we can prepare for it.

### CODE REVIEW

**Comment by Stebalien** [comment]
While it's an important optimization, it's not a part of the contract. Is it not possible to fix your datastore?

**Comment by MichaelMure** [comment]
We could, but at a non-trivial performance cost: (local call potentially cached) vs (local call potentially cached) + (remote call)

Not asking for this behavior to be part of the contract, just to be notified if it ever change.

**Comment by Stebalien** [comment]
Fair enough.

**Comment by Stebalien** [comment]
(I mean, this is so much better than our usual "we know this works, don't touch it" approach)

**Comment by MichaelMure** [comment]
> (I mean, this is so much better than our usual "we know this works, don't touch it" approach)

Both @shazow and I are open source maintainer, we know what's up :)

**Pull request merged**
