### PR TITLE
Use ipld.ErrNotFound

### PR DESCRIPTION
**Pull request by hsanjuan**
Rationale: https://github.com/ipfs/go-ipfs/issues/7074

### CODE REVIEW

**Comment by hsanjuan** [comment]
Note blockstore depends on raw-multihash-enabled datastore already, therefore this cannot be merged until that change is unlocked, or needs to be merged into a pre v1.0.0 branch.

**Comment by hsanjuan** [comment]
Pending https://github.com/ipfs/go-ipld-format/pull/68

**Review by Jorropo — APPROVED** [review]
LGTM

**Comment by Jorropo** [comment]
@orpheuslummis yes, that why this code has been released with a new minor version (not patch). :)
`1.2.0` aa05ad66e513e87ed508cc2e6cfed6b172db9d2f

**Comment by orpheuslummis** [comment]
Thanks for the reference to the PRs. :)
That said [semver](https://semver.org/) indicates that minor version bumps should be backwards compatible. I'm assuming that go-ipfs-blockstore follows semver as this is what go-ipfs is doing as indicated https://github.com/ipfs/go-ipfs/blob/master/docs/releases.md.

**Comment by Jorropo** [comment]
@orpheuslummis a really good point has been raised by someone else.

Golang's way of importing V2 of packages require adding `/v2` to the import path.

Having to bump all imports paths and not just go.mod files for such trivial change sounds like a useless suffering.

**Comment by orpheuslummis** [comment]
I agree. I suggest considering switching to using v0.x.x versioning to avoid future confusions and to be semver-compatible.

**Comment by Jorropo** [comment]
@orpheuslummis I don't like that idea, golang also plays very badly with that, every time people would `go get` it would attempt to download the `1.x` release.

Btw this package got a `1.x` release because at one point they needed two branches because of two projects that were doing things differently, so they maintained a `0.x` branch and a `1.x` branch.

**Comment by orpheuslummis** [comment]
Ah yes. Then I suggest indicating in the README the versioning detail of the repo because it diverges from semver and other go-ipfs projects.

**Comment by Jorropo** [comment]
@orpheuslummis thx for your report, this has been openned:

https://github.com/ipfs/go-ipfs/issues/8832

**Comment by willscott** [comment]
could we in the short term put in an alias of
```
var ErrNotFound = ipld.ErrNotFound
```

**Comment by willscott** [comment]
```
var ErrNotFound = ipld.ErrNotFound{Cid: cid.Undef}
```

**Comment by Jorropo** [comment]
@willscott 

No because the main issue is that code that use `blockstore.ErrNotFound` usually intent to do:
```
err == blockstore.ErrNotFound
```
However that code is broken now because even if that the same error (what the checks want to do), your proposition would only match both identicaly errors and CIDs. (so an `ipld.ErrNotFound` with not `cid.Undef` wouldn't work).

**Comment by hsanjuan** [comment]
> ```
> var ErrNotFound = ipld.ErrNotFound{Cid: cid.Undef}
> ```

iirc there is intent here, in that people should switch to ipld.IsNotFound() checkers etc.

**Comment by willscott** [comment]
Yeah, realized as posting that the blockstore approach doesn't work.

I think the unfortunate thing i'm hitting is that there are blockstore interactions with `go-ipld-prime` that had been built i think with an intention not to depend on `ipld-format`. I'm struggling to figure out what error to return now because i'm hesitant to introduce the ipld-format dependency in ipld-prime.

**Comment by Jorropo** [comment]
> I'm struggling to figure out what error to return now because i'm hesitant to introduce the ipld-format dependency in ipld-prime.

I think there is a good argument to make about moving `ErrNotFound` in `go-ipld-prime`.

Then we can deprecate and add aliases in `go-ipld-format`.

**Pull request merged**
